<?php
/**
 * @file
 *   Linked title field module
 */


/**
 * Implements hook_field_formatter_info().
 */
function linked_title_field_formatter_info() {
  return array(
    'linked_title_wrap' => array(
      'label' => t('Linked and wrapped title (link field support)'),
      'field types' => array('text'),
      'settings' => array(
        'title_style' => '',
        'title_link' => '',
        'title_class' => '',
        'custom_path' => '',
      ),
    ),
  );
}

/**
 * Implements hook_field_formatter_settings_form().
 */
function linked_title_field_formatter_settings_form($field, $instance, $view_mode, $form, &$form_state) {
  $settings = $instance['display'][$view_mode]['settings'];
  $element = title_field_formatter_settings_form($field, $instance, $view_mode, $form, $form_state);

  // We have a special case when used in panels, the instance will have the
  // values for entity_type and bundle set to 'ctools'. In this case we can
  // ignore them and present all the possible link fields as options.
  $entity_type = NULL;
  $bundle = NULL;
  if (!empty($instance['entity_type']) && $instance['entity_type'] != 'ctools') {
    $entity_type = $instance['entity_type'];
  }
  if (!empty($instance['bundle']) && $instance['bundle'] != 'ctools') {
    $bundle = $instance['bundle'];
  }
  $element['title_link']['#options'] = linked_title_get_link_types($entity_type, $bundle);

  // Add option to link to custom path.
  $element['title_link']['#options']['custom_path'] = t('Custom path');
  $element['custom_path'] = array(
    '#type' => 'textfield',
    '#title' => t('Custom path'),
    '#description' => t('Internal drupal path or external URL.'),
    '#default_value' => isset($settings['custom_path']) ? $settings['custom_path'] : '',
    '#states' => array(
      'visible' => array(
        ':input[name="title_link"]' => array('value' => 'custom_path'),
      ),
    ),
  );

  return $element;
}

/**
 * Implements hook_field_formatter_settings_summary().
 */
function linked_title_field_formatter_settings_summary($field, $instance, $view_mode) {
  // Get the summary from image module.
  $summary = title_field_formatter_settings_summary($field, $instance, $view_mode);

  // If link type is other than default ones, it's not included, so we can add it
  // at the end of summary
  $settings = $instance['display'][$view_mode]['settings'];
  if (!empty($settings['title_link']) && !in_array($settings['title_link'], array('content'))) {
    $field_instance = field_info_instance($instance['entity_type'], $settings['title_link'], $instance['bundle']);
    $summary .= '<br />Linked using ' .t(
        '@field_label (@field_name)',
        array(
          '@field_label' => $field_instance['label'], // @todo: i18n support?
          '@field_name' => $field_instance['field_name'],
        )
      );
  }

  return $summary;
}

/**
 * Implements hook_field_formatter_view().
 */
function linked_title_field_formatter_view($entity_type, $entity, $field, $instance, $langcode, $items, $display) {
  $settings = $display['settings'];
  //$output = isset($items[0]) ? $items[0]['safe_value'] : '';
  // We use the value here, the safe_value escapes the aphostrophes.
  // @see http://jira.amazeelabs.com/browse/VET-284
  $output = isset($items[0]) ? $items[0]['value'] : '';

  if (!empty($output) && !empty($settings['title_link'])) {
    if($settings['title_link'] == 'content') {
      $uri = entity_uri($entity_type, $entity);
      $output = l($output, $uri['path'], array('html' => TRUE));
    }
    elseif ($settings['title_link'] == 'custom_path') {
      $output = l($output, $settings['custom_path'], array('html' => TRUE));
    }
    else {
      // The setting looks like this now: content_type::bundle::field_name.
      $words = explode('::', $settings['title_link']);
      if (count($words) == 3) {
        $field_name = $words[2];
      }
      else {
        // For backward compatibility, we still use the old setting if we could
        // not split the title_link.
        $field_name = $settings['title_link'];
      }
      $field_language = field_language($entity_type, $entity, $field_name, $langcode);
      if (isset($entity->{$field_name}[$field_language][0]['url'])) {
        $link_options = $entity->{$field_name}[$field_language][0];
        $link_url = $link_options['url']; unset($link_options['url']);

        if (isset($link_options['title'])) {
          $link_options['attributes']['title'] = $link_options['title'];
        }

        $output = l($output, $link_url, $link_options);
      }
      else {
        // When there is no link, wrapp it in a span.
        $output = '<span class="no-url">' . $output . '</span>';
      }
    }
  }

  $wrap_tag = empty($settings['title_style']) ? '_none' : $settings['title_style'];

  if ($wrap_tag != '_none') {
    $element = array(
      'element' => array(
        '#tag' => $wrap_tag,
        '#value' => $output,
      ),
    );

    if (!empty($settings['title_class'])) {
      $element['#attributes'] = array('class' => $settings['title_class']);
    }

    $output = theme('html_tag', $element);
  }

  $element = array(
    array(
      '#markup' => $output,
    ),
  );

  return $element;
}

/**
 * Get link options for a given entity type and bundle
 *
 * @param string $entity_type
 *   Entity type
 * @param string $bundle
 *   Entity bundle
 *
 * @return array
 *   List of link types that can be used
 */
function linked_title_get_link_types($entity_type = NULL, $bundle = NULL) {
  // Default link types
  $link_types = array(
    'content' => t('Linked to content'),
  );

  $field_instances = field_info_instances();
  foreach($field_instances as $content_type => $bundles) {
    foreach($bundles as $bundle_name => $bundle_instances) {
      // If we have to filter for entity types or bundles, we do it now.
      if (isset($entity_type) && $entity_type != $content_type) {
        continue;
      }
      if (isset($bundle) && $bundle_name != $bundle) {
        continue;
      }
      foreach($bundle_instances as $field_instance) {
        $field_info = field_info_field($field_instance['field_name']);
        if ($field_info['type'] == 'link_field') {
          $link_types[$content_type . '::' . $bundle_name . '::' . $field_instance['field_name']] = t(
            '@field_label (@field_name) from: @content_type (@bundle)',
            array(
              '@field_label' => $field_instance['label'], // @todo: i18n support?
              '@field_name' => $field_instance['field_name'],
              '@content_type' => $content_type,
              '@bundle' => $bundle_name,
            )
          );
        }
      }
    }
  }

  return $link_types;
}